### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ashraful1980** [mvrozanti/BTC-PrivToPub#1]
root@kali:~/Desktop/BTC-PrivToPub# pip install request
Requirement already satisfied: request in /usr/local/lib/python2.7/dist-packages (2019.4.13)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from request) (44.0.0)
Requirement already satisfied: get in /usr/local/lib/python2.7/dist-packages (from request) (2019.4.13)
Requirement already satisfied: post in /usr/local/lib/python2.7/dist-packages (from request) (2019.4.13)
Requirement already satisfied: query-string in /usr/local/lib/python2.7/dist-packages (from get->request) (2019.4.13)
Requirement already satisfied: public in /usr/local/lib/python2.7/dist-packages (from query-string->get->request) (2019.4.13)
root@kali:~/Desktop/BTC-PrivToPub# python genaddresses.py
Traceback (most recent call last):
  File "genaddresses.py", line 7, in <module>
    from urllib import request
ImportError: cannot import name request

root@kali:~/Desktop/BTC-PrivToPub# pip install request
Requirement already satisfied: request in /usr/local/lib/python2.7/dist-packages (2019.4.13)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from request) (44.0.0)
Requirement already satisfied: get in /usr/local/lib/python2.7/dist-packages (from request) (2019.4.13)
Requirement already satisfied: post in /usr/local/lib/python2.7/dist-packages (from request) (2019.4.13)
Requirement already satisfied: query-string in /usr/local/lib/python2.7/dist-packages (from get->request) (2019.4.13)
Requirement already satisfied: public in /usr/local/lib/python2.7/dist-packages (from query-string->get->request) (2019.4.13)
root@kali:~/Desktop/BTC-PrivToPub# python3 genaddresses.py
Traceback (most recent call last):
  File "genaddresses.py", line 375, in <module>
    walletBalance = json.loads(request.urlopen("https://blockchain.info/rawaddr/{}".format(keypair['public'])).read().decode('utf-8'))['final_balance']/100000000
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
root@kali:~/Desktop/BTC-PrivToPub# 

So please help to run the script....

**Comment by mvrozanti** [comment]
HTTPError 429 -  you're making too many requests. Looks like your computer can make more requests per second than mine. Or you're running more than one instance.
